name: o_driver
description: A new Flutter project.

publish_to: "none"

version: 0.0.3+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  hive_flutter: ^1.1.0
  page_transition: ^2.0.9
  flutter_screenutil: ^5.9.0
  logger: ^1.1.0
  flutter_svg: ^1.1.3
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  url_launcher: ^6.1.6
  image_picker: ^0.8.6
  expandable: ^5.0.1
  flutter_slidable: ^3.1.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0
  multicast_dns: ^0.3.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
